import { DrawerMethod } from './drawer';
// @ts-nocheck
import { MessageMethod } from './message';
import { ModalMethod } from './modal';
import { NotificationMethod } from './notification';

declare module 'vue' {
  export interface GlobalComponents {
    AAffix: (typeof import('@sdata/web-vue'))['Affix'];
    AAlert: (typeof import('@sdata/web-vue'))['Alert'];
    AAnchor: (typeof import('@sdata/web-vue'))['Anchor'];
    AAnchorLink: (typeof import('@sdata/web-vue'))['AnchorLink'];
    AAutoComplete: (typeof import('@sdata/web-vue'))['AutoComplete'];
    AAvatar: (typeof import('@sdata/web-vue'))['Avatar'];
    AAvatarGroup: (typeof import('@sdata/web-vue'))['AvatarGroup'];
    ABackTop: (typeof import('@sdata/web-vue'))['BackTop'];
    ABadge: (typeof import('@sdata/web-vue'))['Badge'];
    ABreadcrumb: (typeof import('@sdata/web-vue'))['Breadcrumb'];
    ABreadcrumbItem: (typeof import('@sdata/web-vue'))['BreadcrumbItem'];
    AButton: (typeof import('@sdata/web-vue'))['Button'];
    AButtonGroup: (typeof import('@sdata/web-vue'))['ButtonGroup'];
    ACalendar: (typeof import('@sdata/web-vue'))['Calendar'];
    ACard: (typeof import('@sdata/web-vue'))['Card'];
    ACardMeta: (typeof import('@sdata/web-vue'))['CardMeta'];
    ACardGrid: (typeof import('@sdata/web-vue'))['CardGrid'];
    ACarousel: (typeof import('@sdata/web-vue'))['Carousel'];
    ACarouselItem: (typeof import('@sdata/web-vue'))['CarouselItem'];
    ACascader: (typeof import('@sdata/web-vue'))['Cascader'];
    ACascaderPanel: (typeof import('@sdata/web-vue'))['CascaderPanel'];
    ACheckbox: (typeof import('@sdata/web-vue'))['Checkbox'];
    ACheckboxGroup: (typeof import('@sdata/web-vue'))['CheckboxGroup'];
    ACollapse: (typeof import('@sdata/web-vue'))['Collapse'];
    ACollapseItem: (typeof import('@sdata/web-vue'))['CollapseItem'];
    AColorPicker: (typeof import('@sdata/web-vue'))['ColorPicker'];
    AComment: (typeof import('@sdata/web-vue'))['Comment'];
    AConfigProvider: (typeof import('@sdata/web-vue'))['ConfigProvider'];
    ADatePicker: (typeof import('@sdata/web-vue'))['DatePicker'];
    AWeekPicker: (typeof import('@sdata/web-vue'))['WeekPicker'];
    AMonthPicker: (typeof import('@sdata/web-vue'))['MonthPicker'];
    AYearPicker: (typeof import('@sdata/web-vue'))['YearPicker'];
    AQuarterPicker: (typeof import('@sdata/web-vue'))['QuarterPicker'];
    ARangePicker: (typeof import('@sdata/web-vue'))['RangePicker'];
    ADescriptions: (typeof import('@sdata/web-vue'))['Descriptions'];
    ADescriptionsItem: (typeof import('@sdata/web-vue'))['DescriptionsItem'];
    ADivider: (typeof import('@sdata/web-vue'))['Divider'];
    ADrawer: (typeof import('@sdata/web-vue'))['Drawer'];
    ADropdown: (typeof import('@sdata/web-vue'))['Dropdown'];
    ADoption: (typeof import('@sdata/web-vue'))['Doption'];
    ADgroup: (typeof import('@sdata/web-vue'))['Dgroup'];
    ADsubmenu: (typeof import('@sdata/web-vue'))['Dsubmenu'];
    AEmpty: (typeof import('@sdata/web-vue'))['Empty'];
    AForm: (typeof import('@sdata/web-vue'))['Form'];
    AFormItem: (typeof import('@sdata/web-vue'))['FormItem'];
    AGrid: (typeof import('@sdata/web-vue'))['Grid'];
    AGridItem: (typeof import('@sdata/web-vue'))['GridItem'];
    ACol: (typeof import('@sdata/web-vue'))['Col'];
    ARow: (typeof import('@sdata/web-vue'))['Row'];
    AImage: (typeof import('@sdata/web-vue'))['Image'];
    AImagePreview: (typeof import('@sdata/web-vue'))['ImagePreview'];
    AImagePreviewAction: (typeof import('@sdata/web-vue'))['ImagePreviewAction'];
    AImagePreviewGroup: (typeof import('@sdata/web-vue'))['ImagePreviewGroup'];
    AInput: (typeof import('@sdata/web-vue'))['Input'];
    AInputGroup: (typeof import('@sdata/web-vue'))['InputGroup'];
    AInputSearch: (typeof import('@sdata/web-vue'))['InputSearch'];
    AInputPassword: (typeof import('@sdata/web-vue'))['InputPassword'];
    AInputNumber: (typeof import('@sdata/web-vue'))['InputNumber'];
    AInputTag: (typeof import('@sdata/web-vue'))['InputTag'];
    ALayout: (typeof import('@sdata/web-vue'))['Layout'];
    ALayoutHeader: (typeof import('@sdata/web-vue'))['LayoutHeader'];
    ALayoutContent: (typeof import('@sdata/web-vue'))['LayoutContent'];
    ALayoutFooter: (typeof import('@sdata/web-vue'))['LayoutFooter'];
    ALayoutSider: (typeof import('@sdata/web-vue'))['LayoutSider'];
    ALink: (typeof import('@sdata/web-vue'))['Link'];
    AList: (typeof import('@sdata/web-vue'))['List'];
    AListItem: (typeof import('@sdata/web-vue'))['ListItem'];
    AListItemMeta: (typeof import('@sdata/web-vue'))['ListItemMeta'];
    AMention: (typeof import('@sdata/web-vue'))['Mention'];
    AMenu: (typeof import('@sdata/web-vue'))['Menu'];
    AMenuItem: (typeof import('@sdata/web-vue'))['MenuItem'];
    AMenuItemGroup: (typeof import('@sdata/web-vue'))['MenuItemGroup'];
    ASubMenu: (typeof import('@sdata/web-vue'))['SubMenu'];
    AModal: (typeof import('@sdata/web-vue'))['Modal'];
    APageHeader: (typeof import('@sdata/web-vue'))['PageHeader'];
    APagination: (typeof import('@sdata/web-vue'))['Pagination'];
    APopconfirm: (typeof import('@sdata/web-vue'))['Popconfirm'];
    APopover: (typeof import('@sdata/web-vue'))['Popover'];
    AProgress: (typeof import('@sdata/web-vue'))['Progress'];
    ARadio: (typeof import('@sdata/web-vue'))['Radio'];
    ARadioGroup: (typeof import('@sdata/web-vue'))['RadioGroup'];
    ARate: (typeof import('@sdata/web-vue'))['Rate'];
    AResizeBox: (typeof import('@sdata/web-vue'))['ResizeBox'];
    AResult: (typeof import('@sdata/web-vue'))['Result'];
    ASelect: (typeof import('@sdata/web-vue'))['Select'];
    AOption: (typeof import('@sdata/web-vue'))['Option'];
    AOptgroup: (typeof import('@sdata/web-vue'))['Optgroup'];
    ASkeleton: (typeof import('@sdata/web-vue'))['Skeleton'];
    ASkeletonLine: (typeof import('@sdata/web-vue'))['SkeletonLine'];
    ASkeletonShape: (typeof import('@sdata/web-vue'))['SkeletonShape'];
    ASlider: (typeof import('@sdata/web-vue'))['Slider'];
    ASpace: (typeof import('@sdata/web-vue'))['Space'];
    ASpin: (typeof import('@sdata/web-vue'))['Spin'];
    ASplit: (typeof import('@sdata/web-vue'))['Split'];
    AStatistic: (typeof import('@sdata/web-vue'))['Statistic'];
    ACountdown: (typeof import('@sdata/web-vue'))['Countdown'];
    ASteps: (typeof import('@sdata/web-vue'))['Steps'];
    AStep: (typeof import('@sdata/web-vue'))['Step'];
    ASwitch: (typeof import('@sdata/web-vue'))['Switch'];
    ATable: (typeof import('@sdata/web-vue'))['Table'];
    AThead: (typeof import('@sdata/web-vue'))['Thead'];
    ATd: (typeof import('@sdata/web-vue'))['Td'];
    ATh: (typeof import('@sdata/web-vue'))['Th'];
    ATr: (typeof import('@sdata/web-vue'))['Tr'];
    ATbody: (typeof import('@sdata/web-vue'))['Tbody'];
    ATableColumn: (typeof import('@sdata/web-vue'))['TableColumn'];
    ATabs: (typeof import('@sdata/web-vue'))['Tabs'];
    ATabPane: (typeof import('@sdata/web-vue'))['TabPane'];
    ATag: (typeof import('@sdata/web-vue'))['Tag'];
    ATextarea: (typeof import('@sdata/web-vue'))['Textarea'];
    ATimePicker: (typeof import('@sdata/web-vue'))['TimePicker'];
    ATimeline: (typeof import('@sdata/web-vue'))['Timeline'];
    ATimelineItem: (typeof import('@sdata/web-vue'))['TimelineItem'];
    ATooltip: (typeof import('@sdata/web-vue'))['Tooltip'];
    ATransfer: (typeof import('@sdata/web-vue'))['Transfer'];
    ATree: (typeof import('@sdata/web-vue'))['Tree'];
    ATreeSelect: (typeof import('@sdata/web-vue'))['TreeSelect'];
    ATrigger: (typeof import('@sdata/web-vue'))['Trigger'];
    ATypography: (typeof import('@sdata/web-vue'))['Typography'];
    ATypographyParagraph: (typeof import('@sdata/web-vue'))['TypographyParagraph'];
    ATypographyTitle: (typeof import('@sdata/web-vue'))['TypographyTitle'];
    ATypographyText: (typeof import('@sdata/web-vue'))['TypographyText'];
    AUpload: (typeof import('@sdata/web-vue'))['Upload'];
    AVerificationCode: (typeof import('@sdata/web-vue'))['VerificationCode'];
    AWatermark: (typeof import('@sdata/web-vue'))['Watermark'];
  }

  export interface ComponentCustomProperties {
    $message: MessageMethod;
    $notification: NotificationMethod;
    $modal: ModalMethod;
    $drawer: DrawerMethod;
  }
}

export {};
