import { DrawerMethod } from './drawer';
// @ts-nocheck
import { MessageMethod } from './message';
import { ModalMethod } from './modal';
import { NotificationMethod } from './notification';

declare module 'vue' {
  export interface GlobalComponents {
    SdAffix: (typeof import('@sdata/web-vue'))['Affix'];
    SdAlert: (typeof import('@sdata/web-vue'))['Alert'];
    SdAnchor: (typeof import('@sdata/web-vue'))['Anchor'];
    SdAnchorLink: (typeof import('@sdata/web-vue'))['AnchorLink'];
    SdAutoComplete: (typeof import('@sdata/web-vue'))['AutoComplete'];
    SdAvatar: (typeof import('@sdata/web-vue'))['Avatar'];
    SdAvatarGroup: (typeof import('@sdata/web-vue'))['AvatarGroup'];
    SdBackTop: (typeof import('@sdata/web-vue'))['BackTop'];
    SdBadge: (typeof import('@sdata/web-vue'))['Badge'];
    SdBreadcrumb: (typeof import('@sdata/web-vue'))['Breadcrumb'];
    SdBreadcrumbItem: (typeof import('@sdata/web-vue'))['BreadcrumbItem'];
    SdButton: (typeof import('@sdata/web-vue'))['Button'];
    SdButtonGroup: (typeof import('@sdata/web-vue'))['ButtonGroup'];
    SdCalendar: (typeof import('@sdata/web-vue'))['Calendar'];
    SdCard: (typeof import('@sdata/web-vue'))['Card'];
    SdCardMeta: (typeof import('@sdata/web-vue'))['CardMeta'];
    SdCardGrid: (typeof import('@sdata/web-vue'))['CardGrid'];
    SdCarousel: (typeof import('@sdata/web-vue'))['Carousel'];
    SdCarouselItem: (typeof import('@sdata/web-vue'))['CarouselItem'];
    SdCascader: (typeof import('@sdata/web-vue'))['Cascader'];
    SdCascaderPanel: (typeof import('@sdata/web-vue'))['CascaderPanel'];
    SdCheckbox: (typeof import('@sdata/web-vue'))['Checkbox'];
    SdCheckboxGroup: (typeof import('@sdata/web-vue'))['CheckboxGroup'];
    SdCollapse: (typeof import('@sdata/web-vue'))['Collapse'];
    SdCollapseItem: (typeof import('@sdata/web-vue'))['CollapseItem'];
    SdColorPicker: (typeof import('@sdata/web-vue'))['ColorPicker'];
    SdComment: (typeof import('@sdata/web-vue'))['Comment'];
    SdConfigProvider: (typeof import('@sdata/web-vue'))['ConfigProvider'];
    SdDatePicker: (typeof import('@sdata/web-vue'))['DatePicker'];
    SdWeekPicker: (typeof import('@sdata/web-vue'))['WeekPicker'];
    SdMonthPicker: (typeof import('@sdata/web-vue'))['MonthPicker'];
    SdYearPicker: (typeof import('@sdata/web-vue'))['YearPicker'];
    SdQuarterPicker: (typeof import('@sdata/web-vue'))['QuarterPicker'];
    SdRangePicker: (typeof import('@sdata/web-vue'))['RangePicker'];
    SdDescriptions: (typeof import('@sdata/web-vue'))['Descriptions'];
    SdDescriptionsItem: (typeof import('@sdata/web-vue'))['DescriptionsItem'];
    SdDivider: (typeof import('@sdata/web-vue'))['Divider'];
    SdDrawer: (typeof import('@sdata/web-vue'))['Drawer'];
    SdDropdown: (typeof import('@sdata/web-vue'))['Dropdown'];
    SdDoption: (typeof import('@sdata/web-vue'))['Doption'];
    SdDgroup: (typeof import('@sdata/web-vue'))['Dgroup'];
    SdDsubmenu: (typeof import('@sdata/web-vue'))['Dsubmenu'];
    SdEmpty: (typeof import('@sdata/web-vue'))['Empty'];
    SdForm: (typeof import('@sdata/web-vue'))['Form'];
    SdFormItem: (typeof import('@sdata/web-vue'))['FormItem'];
    SdGrid: (typeof import('@sdata/web-vue'))['Grid'];
    SdGridItem: (typeof import('@sdata/web-vue'))['GridItem'];
    SdCol: (typeof import('@sdata/web-vue'))['Col'];
    SdRow: (typeof import('@sdata/web-vue'))['Row'];
    SdImage: (typeof import('@sdata/web-vue'))['Image'];
    SdImagePreview: (typeof import('@sdata/web-vue'))['ImagePreview'];
    SdImagePreviewAction: (typeof import('@sdata/web-vue'))['ImagePreviewAction'];
    SdImagePreviewGroup: (typeof import('@sdata/web-vue'))['ImagePreviewGroup'];
    SdInput: (typeof import('@sdata/web-vue'))['Input'];
    SdInputGroup: (typeof import('@sdata/web-vue'))['InputGroup'];
    SdInputSearch: (typeof import('@sdata/web-vue'))['InputSearch'];
    SdInputPassword: (typeof import('@sdata/web-vue'))['InputPassword'];
    SdInputNumber: (typeof import('@sdata/web-vue'))['InputNumber'];
    SdInputTag: (typeof import('@sdata/web-vue'))['InputTag'];
    SdLayout: (typeof import('@sdata/web-vue'))['Layout'];
    SdLayoutHeader: (typeof import('@sdata/web-vue'))['LayoutHeader'];
    SdLayoutContent: (typeof import('@sdata/web-vue'))['LayoutContent'];
    SdLayoutFooter: (typeof import('@sdata/web-vue'))['LayoutFooter'];
    SdLayoutSider: (typeof import('@sdata/web-vue'))['LayoutSider'];
    SdLink: (typeof import('@sdata/web-vue'))['Link'];
    SdList: (typeof import('@sdata/web-vue'))['List'];
    SdListItem: (typeof import('@sdata/web-vue'))['ListItem'];
    SdListItemMeta: (typeof import('@sdata/web-vue'))['ListItemMeta'];
    SdMention: (typeof import('@sdata/web-vue'))['Mention'];
    SdMenu: (typeof import('@sdata/web-vue'))['Menu'];
    SdMenuItem: (typeof import('@sdata/web-vue'))['MenuItem'];
    SdMenuItemGroup: (typeof import('@sdata/web-vue'))['MenuItemGroup'];
    SdSubMenu: (typeof import('@sdata/web-vue'))['SubMenu'];
    SdModal: (typeof import('@sdata/web-vue'))['Modal'];
    SdPageHeader: (typeof import('@sdata/web-vue'))['PageHeader'];
    SdPagination: (typeof import('@sdata/web-vue'))['Pagination'];
    SdPopconfirm: (typeof import('@sdata/web-vue'))['Popconfirm'];
    SdPopover: (typeof import('@sdata/web-vue'))['Popover'];
    SdProgress: (typeof import('@sdata/web-vue'))['Progress'];
    SdRadio: (typeof import('@sdata/web-vue'))['Radio'];
    SdRadioGroup: (typeof import('@sdata/web-vue'))['RadioGroup'];
    SdRate: (typeof import('@sdata/web-vue'))['Rate'];
    SdResizeBox: (typeof import('@sdata/web-vue'))['ResizeBox'];
    SdResult: (typeof import('@sdata/web-vue'))['Result'];
    SdSelect: (typeof import('@sdata/web-vue'))['Select'];
    SdOption: (typeof import('@sdata/web-vue'))['Option'];
    SdOptgroup: (typeof import('@sdata/web-vue'))['Optgroup'];
    SdSkeleton: (typeof import('@sdata/web-vue'))['Skeleton'];
    SdSkeletonLine: (typeof import('@sdata/web-vue'))['SkeletonLine'];
    SdSkeletonShape: (typeof import('@sdata/web-vue'))['SkeletonShape'];
    SdSlider: (typeof import('@sdata/web-vue'))['Slider'];
    SdSpace: (typeof import('@sdata/web-vue'))['Space'];
    SdSpin: (typeof import('@sdata/web-vue'))['Spin'];
    SdSplit: (typeof import('@sdata/web-vue'))['Split'];
    SdStatistic: (typeof import('@sdata/web-vue'))['Statistic'];
    SdCountdown: (typeof import('@sdata/web-vue'))['Countdown'];
    SdSteps: (typeof import('@sdata/web-vue'))['Steps'];
    SdStep: (typeof import('@sdata/web-vue'))['Step'];
    SdSwitch: (typeof import('@sdata/web-vue'))['Switch'];
    SdTable: (typeof import('@sdata/web-vue'))['Table'];
    SdThead: (typeof import('@sdata/web-vue'))['Thead'];
    SdTd: (typeof import('@sdata/web-vue'))['Td'];
    SdTh: (typeof import('@sdata/web-vue'))['Th'];
    SdTr: (typeof import('@sdata/web-vue'))['Tr'];
    SdTbody: (typeof import('@sdata/web-vue'))['Tbody'];
    SdTableColumn: (typeof import('@sdata/web-vue'))['TableColumn'];
    SdTabs: (typeof import('@sdata/web-vue'))['Tabs'];
    SdTabPane: (typeof import('@sdata/web-vue'))['TabPane'];
    SdTag: (typeof import('@sdata/web-vue'))['Tag'];
    SdTextarea: (typeof import('@sdata/web-vue'))['Textarea'];
    SdTimePicker: (typeof import('@sdata/web-vue'))['TimePicker'];
    SdTimeline: (typeof import('@sdata/web-vue'))['Timeline'];
    SdTimelineItem: (typeof import('@sdata/web-vue'))['TimelineItem'];
    SdTooltip: (typeof import('@sdata/web-vue'))['Tooltip'];
    SdTransfer: (typeof import('@sdata/web-vue'))['Transfer'];
    SdTree: (typeof import('@sdata/web-vue'))['Tree'];
    SdTreeSelect: (typeof import('@sdata/web-vue'))['TreeSelect'];
    SdTrigger: (typeof import('@sdata/web-vue'))['Trigger'];
    SdTypography: (typeof import('@sdata/web-vue'))['Typography'];
    SdTypographyParagraph: (typeof import('@sdata/web-vue'))['TypographyParagraph'];
    SdTypographyTitle: (typeof import('@sdata/web-vue'))['TypographyTitle'];
    SdTypographyText: (typeof import('@sdata/web-vue'))['TypographyText'];
    SdUpload: (typeof import('@sdata/web-vue'))['Upload'];
    SdVerificationCode: (typeof import('@sdata/web-vue'))['VerificationCode'];
    SdWatermark: (typeof import('@sdata/web-vue'))['Watermark'];
  }

  export interface ComponentCustomProperties {
    $message: MessageMethod;
    $notification: NotificationMethod;
    $modal: ModalMethod;
    $drawer: DrawerMethod;
  }
}

export {};
