import type { UserConfig } from 'czg';

export default {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'header-max-length': [1, 'always', 128],
    'body-max-length': [1, 'always', 1000],
    'footer-max-length': [1, 'always', 1000],
    'body-max-line-length': [1, 'always', 1000],
    'footer-max-line-length': [1, 'always', 1000],
    'type-enum': [
      1,
      'always',
      [
        'build',
        'chore',
        'ci',
        'docs',
        'feat',
        'fix',
        'perf',
        'refactor',
        'revert',
        'style',
        'test',
        'wip',
        'release',
      ],
    ],
  },
  prompt: {
    messages: {
      type: '选择您要提交的更改类型：',
      scope: '选择本次变更的范围（可选）：',
      customScope: '请输入本次变更的范围：',
      subject: '请用简短的语句描述这一变化：\n',
      body: '详细描述变更（可选，使用 "|" 换行）：\n',
      breaking: '描述不向后兼容的变更（可选，使用 "|" 换行）：\n',
      footerPrefixesSelect: '选择关联 issue 的操作：',
      customFooterPrefix: '请输入自定义 issue 前缀：',
      footer: '请输入关联 issue 编号，例如 #123：',
      confirmCommit: '是否确认提交以上内容？',
    },
    types: [
      {
        value: 'build',
        name: 'build: 修改构建系统或依赖，例如构建配置、依赖升级、Node 版本调整',
        emoji: '🏗️',
      },
      {
        value: 'chore',
        name: 'chore: 其他维护工作，例如辅助工具或仓库管理配置调整',
        emoji: '🧹',
      },
      {
        value: 'ci',
        name: 'ci: 与 CI 有关的更改',
        emoji: '🤖',
      },
      {
        value: 'docs',
        name: 'docs: 仅更改文档',
        emoji: '✏️',
      },
      {
        value: 'feat',
        name: 'feat: 新功能',
        emoji: '🆕',
      },
      {
        value: 'fix',
        name: 'fix: Bug 修复',
        emoji: '🐛',
      },
      {
        value: 'perf',
        name: 'perf: 改进性能的代码变更',
        emoji: '⚡️',
      },
      {
        value: 'refactor',
        name: 'refactor: 代码重构，不新增功能也不修复缺陷',
        emoji: '💡',
      },
      {
        value: 'revert',
        name: 'revert: 撤回之前的 commit',
        emoji: '🔙',
      },
      {
        value: 'style',
        name: 'style: 不影响代码含义的格式调整，例如缩进、空格、分号；不指界面样式',
        emoji: '{};',
      },
      {
        value: 'test',
        name: 'test: 添加或修正测试',
        emoji: '🧪',
      },
      {
        value: 'wip',
        name: 'wip: 提交尚未完成的工作',
        emoji: '👷',
      },
      {
        value: 'release',
        name: 'release: 创建版本提交',
        emoji: '🔢',
      },
    ],
    useEmoji: true,
    emojiAlign: 'center',
    allowBreakingChanges: [
      'build',
      'chore',
      'ci',
      'docs',
      'feat',
      'fix',
      'perf',
      'refactor',
      'revert',
      'style',
      'test',
      'wip',
      'release',
    ],
    customScopesAlias: '自定义',
    emptyScopesAlias: '跳过',
    customIssuePrefixAlias: '自定义',
    emptyIssuePrefixAlias: '跳过',
    issuePrefixes: [{ value: 'closed', name: 'closed: 关闭关联 issue' }],
  },
} satisfies UserConfig;
