[build]
base = "."
command = "pnpm install --frozen-lockfile && pnpm run init && pnpm --filter @sd-design/sd-vue-docs run docs:build"
publish = "packages/sd-vue-docs/.vitepress/dist"

[build.environment]
COREPACK_ENABLE_AUTO_PIN = "1"
