[build]
base = "."
command = "corepack enable && pnpm install --frozen-lockfile && pnpm run build:docs --verbose"
publish = "packages/sd-vue-docs/dist"

[build.environment]
COREPACK_ENABLE_AUTO_PIN = "1"
