packages:
  - 'packages/*'

onlyBuiltDependencies:
  - 'core-js'
  - 'core-js-pure'
  - 'esbuild'
  - 'sharp'
  - 'simple-git-hooks'
  - 'unrs-resolver'
  - 'vue-demi'
  - 'vue-inbrowser-compiler-demi'
