import { defineComponent, h, ref } from 'vue';

import type { TableColumnData } from '../../table';

import { configProviderInjectionKey } from '../../config-provider/context';
import BasicCrudTable from '../basic-crud-table.vue';

const columns: TableColumnData[] = [{ title: '名称', dataIndex: 'name' }];

describe('BasicCrudTable', () => {
  it('透传 spinProps 到列表加载遮罩', () => {
    cy.mount(BasicCrudTable, {
      props: {
        columns,
        loading: true,
        fetchTableOnMounted: false,
        spinProps: { tip: '数据加载中', size: 26 },
      },
    });
    cy.get('.sd-basic-crud-table-body > .sd-spin-mask .sd-spin-tip').should(
      'have.text',
      '数据加载中',
    );
    cy.get('.sd-basic-crud-table-body > .sd-spin-mask .sd-spin-icon').should(
      'have.css',
      'font-size',
      '26px',
    );
  });

  it('合并 ConfigProvider 的 basicCrudTableSpinProps 与局部 spinProps', () => {
    cy.mount(BasicCrudTable, {
      props: {
        columns,
        loading: true,
        fetchTableOnMounted: false,
        spinProps: { tip: '局部提示' },
      },
      global: {
        provide: {
          [configProviderInjectionKey as symbol]: {
            slots: {},
            spinProps: { size: 12 },
            basicCrudTableSpinProps: { size: 28, dot: true },
          },
        },
      },
    });
    cy.get('.sd-basic-crud-table-body > .sd-spin-mask .sd-spin-tip').should(
      'have.text',
      '局部提示',
    );
    cy.get('.sd-basic-crud-table-body > .sd-spin-mask .sd-dot-loading').should('exist');
    cy.get('.sd-basic-crud-table-body > .sd-spin-mask .sd-spin-icon').should(
      'have.css',
      'font-size',
      '28px',
    );
  });

  it('加载数据并透传查询参数', () => {
    const fetchTableApi = cy.stub().resolves({ data: [{ key: 1, name: '监控项' }], total: 1 });
    cy.mount(BasicCrudTable, { props: { columns, fetchTableApi } });
    cy.wrap(fetchTableApi).should('have.been.calledWithMatch', { current: 1, pageSize: 10 });
    cy.contains('监控项').should('be.visible');
  });

  // Generated by Cypress Author on 2026-07-20.
  it('配置全局默认分页大小 → 首次请求使用该分页大小', () => {
    const fetchTableApi = cy.stub().resolves({ data: [], total: 0 });
    cy.mount(BasicCrudTable, {
      props: { columns, fetchTableApi },
      global: {
        provide: {
          [configProviderInjectionKey as symbol]: {
            slots: {},
            pagination: { defaultPageSize: 50 },
          },
        },
      },
    });
    cy.wrap(fetchTableApi).should('have.been.calledWithMatch', { current: 1, pageSize: 50 });
  });

  it('fullHeight 占满父级高度，表格区域内部滚动', () => {
    // 包一层定高父级，验证「占满父级 + 内容内部滚动」而非被内容撑开或裁切
    const Wrapper = defineComponent({
      render() {
        return h(
          'div',
          { style: 'height: 400px' },
          h(BasicCrudTable, {
            columns,
            tableData: Array.from({ length: 20 }, (_, index) => ({
              key: index,
              name: `监控项 ${index + 1}`,
            })),
            fetchTableOnMounted: false,
            fullHeight: true,
            // 关掉分页，让 20 行全部渲染以触发纵向溢出
            tableProps: { pagination: false, scroll: { x: 800 } },
          }),
        );
      },
    });
    cy.mount(Wrapper);

    cy.get('.sd-basic-crud-table').should('have.class', 'sd-basic-crud-table-full-height');
    // 行为：crud table 高度等于父级，而不是被 20 行撑高
    cy.get('.sd-basic-crud-table').then(($el) => {
      const el = $el[0];
      expect(el.offsetHeight, '占满父级高度').to.be.closeTo(el.parentElement!.offsetHeight, 1);
    });
    // 行为：表格内容（20 行）超出可视区——body 被约束在剩余空间内，
    // scrollHeight > clientHeight 说明多出的行进入内部滚动，而非把组件撑高
    cy.get('.sd-table-body').should(($body) => {
      expect($body[0].scrollHeight, '表格内部存在溢出/可滚动').to.be.greaterThan(
        $body[0].clientHeight,
      );
    });
  });

  it('触发新建与编辑', () => {
    const onCreate = cy.spy().as('create');
    const onEdit = cy.spy().as('edit');
    cy.mount(BasicCrudTable, {
      props: {
        columns,
        tableData: [{ key: 1, name: '监控项' }],
        fetchTableOnMounted: false,
        openCreateModal: false,
        onCreate,
        onEdit,
      },
    });
    cy.contains('新建').click();
    cy.get('@create').should('have.been.calledOnce');
    cy.contains('编辑').click();
    cy.get('@edit').should('have.been.calledWithMatch', { name: '监控项' });
  });

  it('在重置后渲染 middle，且不依赖新建按钮显示', () => {
    cy.mount(BasicCrudTable, {
      props: {
        columns,
        fetchTableOnMounted: false,
      },
      slots: {
        toolbar__action_middle: '<span data-testid="action-middle">中间</span>',
        toolbar__action_append: '<span data-testid="action-append">追加</span>',
      },
    });

    cy.get('.sd-toolbar-actions')
      .children()
      .then(($actions) => {
        expect([...$actions].map((action) => action.textContent?.trim())).to.deep.equal([
          '查询',
          '重置',
          '中间',
          '新建',
          '追加',
        ]);
      });

    cy.get('@vue').then(({ wrapper }) => wrapper.setProps({ showCreate: false }));
    cy.get('.sd-toolbar-actions')
      .children()
      .then(($actions) => {
        expect([...$actions].map((action) => action.textContent?.trim())).to.deep.equal([
          '查询',
          '重置',
          '中间',
          '追加',
        ]);
      });
  });

  it('透传所有内置操作按钮的 props', () => {
    const onCreate = cy.spy().as('disabledCreate');
    const onEdit = cy.spy().as('disabledEdit');
    cy.mount(BasicCrudTable, {
      props: {
        columns,
        tableData: [{ key: 1, name: '监控项' }],
        fetchTableOnMounted: false,
        openCreateModal: false,
        searchBtn: { disabled: true },
        resetBtn: { disabled: true },
        createBtn: { disabled: true },
        editBtn: { disabled: true },
        deleteBtn: { disabled: true },
        onCreate,
        onEdit,
      },
    });

    cy.contains('button', '查询').should('be.disabled');
    cy.contains('button', '重置').should('be.disabled');
    cy.contains('button', '新建').should('be.disabled');
    cy.contains('编辑').should('have.class', 'sd-link-disabled').click({ force: true });
    cy.contains('删除').should('have.class', 'sd-link-disabled').click({ force: true });
    cy.get('@disabledCreate').should('not.have.been.called');
    cy.get('@disabledEdit').should('not.have.been.called');
    cy.get('.sd-popconfirm').should('not.exist');
  });

  it('按当前行解析编辑与删除按钮 props', () => {
    const editBtn = cy.stub().callsFake((row: { readonly?: boolean }) => ({
      disabled: row.readonly,
    }));
    const deleteBtn = cy.stub().callsFake((row: { readonly?: boolean }) => ({
      status: row.readonly ? ('warning' as const) : ('success' as const),
    }));
    cy.mount(BasicCrudTable, {
      props: {
        columns,
        tableData: [
          { key: 1, name: '只读项', readonly: true },
          { key: 2, name: '可编辑项', readonly: false },
        ],
        fetchTableOnMounted: false,
        editBtn,
        deleteBtn,
      },
    });

    cy.contains('只读项')
      .parents('.sd-table-tr')
      .within(() => {
        cy.contains('编辑').should('have.class', 'sd-link-disabled');
        cy.contains('删除').should('have.class', 'sd-link-status-warning');
      });
    cy.contains('可编辑项')
      .parents('.sd-table-tr')
      .within(() => {
        cy.contains('编辑').should('not.have.class', 'sd-link-disabled');
        cy.contains('删除').should('have.class', 'sd-link-status-success');
      });
    cy.wrap(editBtn).should('have.been.calledWithMatch', { key: 1, name: '只读项' });
    cy.wrap(deleteBtn).should('have.been.calledWithMatch', { key: 2, name: '可编辑项' });
  });

  it('删除经 popconfirm 确认后调用 deleteApi 并刷新列表', () => {
    const fetchTableApi = cy.stub().resolves({ data: [{ key: 1, name: '监控项' }], total: 1 });
    const deleteApi = cy.stub().resolves();
    cy.mount(BasicCrudTable, {
      props: { columns, fetchTableApi, deleteApi },
    });
    cy.contains('监控项').should('be.visible');
    cy.contains('删除').click();
    cy.get('.sd-popconfirm-footer').should('be.visible').contains('确定').click();
    cy.wrap(deleteApi).should('have.been.calledWithMatch', { name: '监控项' });
    cy.wrap(fetchTableApi).should('have.callCount', 2);
  });

  it('重置后用同步后的筛选值请求，而非旧的筛选值', () => {
    const fetchTableApi = cy.stub().resolves({ data: [], total: 0 });
    // 用 v-model 双向绑定，复现真实使用场景：Toolbar.reset 改 modelValue 后，
    // 父级 v-model 的回写是异步的，handleReset 若不等待会读到旧筛选值。
    const Wrapper = defineComponent({
      setup() {
        const filters = ref<Record<string, unknown>>({ status: '' });
        return { filters };
      },
      render() {
        return h(BasicCrudTable, {
          columns,
          fetchTableApi,
          'toolbarModel': this.filters,
          'onUpdate:toolbarModel': (value: Record<string, unknown>) => {
            this.filters = value;
          },
          'toolbarProps': {
            schemas: [
              {
                field: 'status',
                label: '状态',
                type: 'select',
                componentProps: { options: [{ label: '在线', value: '在线' }] },
              },
            ],
          },
        });
      },
    });
    cy.mount(Wrapper);
    cy.wrap(fetchTableApi).should('have.been.calledWithMatch', { status: '' });
    // 通过 v-model 把筛选改为「在线」（不触发请求）
    cy.get('@vue').then(({ wrapper }) => {
      wrapper.vm.filters = { status: '在线' };
    });
    cy.contains('重置').click();
    // 重置后最后一次请求应使用清空后的筛选值，而不是旧的「在线」
    cy.wrap(fetchTableApi).should((stub) => {
      const calls = stub.getCalls();
      const lastParams = calls[calls.length - 1]?.args[0];
      expect(lastParams, '最后一次请求参数').to.deep.include({ status: '' });
    });
  });

  it('区分子组件属性并完成创建提交', () => {
    const fetchTableApi = cy.stub().resolves({ data: [], total: 0 });
    const createApi = cy.stub().resolves({ id: 1 });
    cy.mount(BasicCrudTable, {
      props: {
        columns,
        fetchTableApi,
        createApi,
        toolbarProps: { showReset: false },
        modalFormProps: {
          schemas: [{ field: 'name', label: '名称', type: 'input', required: true }],
        },
      },
    });
    cy.contains('重置').should('not.exist');
    cy.contains('新建').click();
    cy.get('.sd-modal input').type('新记录');
    cy.get('.sd-modal-footer').contains('确定').click();
    cy.wrap(createApi).should('have.been.calledWithMatch', { name: '新记录' });
    cy.wrap(fetchTableApi).should('have.callCount', 2);
  });
});
